USE [EPDMSuite]
GO

/****** Object:  Table [dbo].[XPORT_QUEUE]    Script Date: 2/23/2023 11:47:02 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[XPORT_QUEUE](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Filename] [nvarchar](500) NULL,
	[DocumentID] int NULL,
	[Vault] nvarchar(200),
	[DataLancio] [datetime] NULL,
	[DataImport] [datetime] NULL,
	[Importato] [smallint] NOT NULL,
 CONSTRAINT [PK_XPORT_QUEUE] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[XPORT_QUEUE] ADD  CONSTRAINT [DF_XPORT_QUEUE_Importato]  DEFAULT ((0)) FOR [Importato]
GO


